import turtle
import time
turtle.pensize(5)
turtle.speed(10)
turtle.pencolor("black")
turtle.circle(50)
turtle.penup()
turtle.goto(50,-50)
turtle.pencolor("orange")
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(80,0)
turtle.pencolor("red")
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(120,-50)
turtle.pencolor("blue")
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(165,0)
turtle.pencolor("green")
turtle.pendown()
turtle.circle(50)
time.sleep(5)

